#!/usr/bin/env python2
'''
Replay server for snmp.
See --help for usage.
'''

from twisted.internet import reactor
import Queue
import sys
import mitmproxy


def main():
    '''
    Parse options, open and read log file, start replay server
    '''
    (opts, _) = mitmproxy.replay_option_parser(1610)

    if opts.inputfile is None:
        print "Need to specify an input file."
        sys.exit(1)
    else:
        log = mitmproxy.Logger()
        if opts.logfile is not None:
            log.open_log(opts.logfile)

        serverq = Queue.Queue()
        clientq = Queue.Queue()
        clientfirst = None

        mitmproxy.logreader(opts.inputfile, serverq, clientq, clientfirst)

        sys.stderr.write(
            'Server running on localhost:%d\n' % opts.localport)
        server = mitmproxy.UDPReplayServer(log, (serverq, clientq),
            opts.delaymod, clientfirst)
        reactor.listenUDP(opts.localport, server)
        reactor.run()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(0)
